packages:
  - packages/*
  - apps/*
  - configs/**/*

catalog:
  '@antfu/eslint-config': ^4.16.1
  '@eslint-react/eslint-plugin': ^1.52.2
  '@tsconfig/node22': ^22.0.2
  '@types/node': ^24.0.4
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  eslint: ^9.29.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20

  prettier-plugin-tailwindcss: ^0.6.13
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vite: ^6.3.5
  vite-plugin-pwa: ^1.0.0
  vue: ^3.5.17
publicHoistPattern:
  - eslint
