packages:
  - packages/*
  - apps/*
  - configs/**/*

catalog:
  "@vitejs/plugin-vue": ^6.0.0
  "@types/node": ^24.0.4
  "@tsconfig/node22": ^22.0.2
  "@vue/tsconfig": ^0.7.0
  vite-plugin-pwa: ^1.0.0
  typescript: ^5.8.3
  vue: ^3.5.17
  vite: ^6.3.5
  unbuild: ^3.5.0
